<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>591bed27-99a9-45a0-b0d8-073697172d0d</elementGuidId>
    <imagePath></imagePath>
    <name>link_MultipleWindows</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[2]/div[1]/div[3]/section[1]/div[12]/div[2]/div[1]/div[1]/h3[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/windows') and equals(@text,'Multiple Windows')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Multiple Windows"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/windows</value>
        <webElementGuid>d978d4d5-7224-48ec-a0b2-6b735a0ba48d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Multiple Windows</value>
        <webElementGuid>d978d4d5-7224-48ec-a0b2-6b735a0ba48d</webElementGuid>
    </webElementProperties>
</WebElementEntity>