<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0480fa83-e9ce-46bb-9811-df8ac717d658</elementGuidId>
    <imagePath></imagePath>
    <name>link_JavaScriptDialogs</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[2]/div[1]/div[3]/section[1]/div[8]/div[1]/div[1]/div[1]/h3[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/js-dialogs') and equals(@text,'JavaScript Dialogs')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="JavaScript Dialogs"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/js-dialogs</value>
        <webElementGuid>d978d4d5-7224-48ec-a0b2-6b735a0ba48d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>JavaScript Dialogs</value>
        <webElementGuid>d978d4d5-7224-48ec-a0b2-6b735a0ba48d</webElementGuid>
    </webElementProperties>
</WebElementEntity>