<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>772e78dc-1cdb-4f07-8f10-08a17330b90d</elementGuidId>
    <imagePath></imagePath>
    <name>link_KeyPresses</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[2]/div[1]/div[3]/section[1]/div[9]/div[4]/div[1]/div[1]/h3[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/key-presses') and equals(@text,'Key Presses')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Key Presses"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/key-presses</value>
        <webElementGuid>d978d4d5-7224-48ec-a0b2-6b735a0ba48d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Key Presses</value>
        <webElementGuid>d978d4d5-7224-48ec-a0b2-6b735a0ba48d</webElementGuid>
    </webElementProperties>
</WebElementEntity>